export const LOG_ACTIONS = {
  // Customers
  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  EDIT_CUSTOMER: "EDIT_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",

  // Products
  CREATE_PRODUCT: "CREATE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",

  // Purchases
  CREATE_PURCHASE: "CREATE_PURCHASE",
  EDIT_PURCHASE: "EDIT_PURCHASE",
  DELETE_PURCHASE: "DELETE_PURCHASE",

  // Contracts
  CREATE_CONTRACT: "CREATE_CONTRACT",
  EDIT_CONTRACT: "EDIT_CONTRACT",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
};
